version: "3.7"
services:
  web:
    container_name: ebay-alert-ws
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - /data/db
    ports:
      - "27017:27017"